services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard port
    labels:
      - "traefik.enable=true"
      ## DNS CHALLENGE
      - "traefik.http.routers.test.tls.certresolver=myresolver"
      - "traefik.http.routers.test.tls.domains[0].main=*.$MY_DOMAIN"
      - "traefik.http.routers.test.tls.domains[0].sans=$MY_DOMAIN"
      ## HTTP REDIRECT
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.entrypoints=websecure"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"
      ## Dashboard
      - "traefik.http.routers.test-dashboard.rule=Host(`traefik.$MY_DOMAIN`)"
      - "traefik.http.routers.test-dashboard.entrypoints=websecure"
      - "traefik.http.routers.test-dashboard.service=api@internal"
      - "traefik.http.routers.test-dashboard.tls.certresolver=myresolver"
      ## Authentik
      - "traefik.http.routers.test-dashboard.middlewares=authentik@file"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./config/certs:/certs"
      - "./dynamic:/dynamic:ro"
    networks:
      - web

networks:
  web:
    driver: overlay
    external: true
