[api]
dashboard = true
insecure = true

[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[providers.docker]
exposedByDefault = false

[providers.file]
directory = "/dynamic"
watch = true

[tls.certificates]
certFile = "/certs/nginx-proxy.crt"
keyFile = "/certs/nginx-proxy.key"

[log]
level = "INFO"
filePath = "/var/log/traefik/traefik.log"

[accessLog]
filePath = "/var/log/traefik/access.log"
