api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/certs/nginx-proxy.crt"
      keyFile: "/certs/nginx-proxy.key"

#middlewares:
#  auth:
#    basicAuth:
#      users:
#        - "admin:$$apr1$$hashedpassword"
